version: '3.8'
services:
    api:
        build: ./customerapi/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1

    web:
        build: ./customerwebapp/
        ports:
            - 3000:3000
        environment:
            PORT: 3000
        depends_on:
            - api
